# Generated by Django 4.1.2 on 2022-10-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FANTASY', 'Fantasy'), ('ADVENTURE', 'Adventure'), ('HORROR', 'Horror')], max_length=30),
        ),
    ]
