# Generated by Django 4.1.2 on 2022-10-28 09:36

from django.db import migrations, models

import Book_Talk.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_book_author_alter_book_review_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='book_images', validators=[Book_Talk.web.validators.ImageMaxSizeValidator(5)]),
        ),
    ]
