# Generated by Django 4.1.2 on 2022-10-28 12:55

import django.db.models.deletion
from django.db import migrations, models

import Book_Talk.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_book_wishing_list_book_wishing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='book_images', validators=[Book_Talk.web.validators.ImageMaxSizeValidator(1)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user'),
        ),
    ]
